apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booklog-api
  template:
    metadata:
      labels:
        app: booklog-api
    spec:
      containers:
        - name: booklog-api
          image: booklog-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_HOST
              value: "mongo-service"
            - name: MONGO_PORT
              value: "27017"
