kind: Service
apiVersion: v1
metadata:
  name: booklog-client-service
spec:
  type: NodePort
  selector:
    app: booklog-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32001
      name: booklog-client-service
